Repository splunk-soar-connectors/mattermost, pull requests merged in 2021-12, with the labels that each got.

#1 PAPP-12188 : Mattermost feature request
  mattermost.json
  mattermost_connector.py
  mattermost_consts.py
  readme.html
  readme.md
  release_notes/unreleased.md
Labels: certified

#3 Mattermost: Resolve merge conflict
  release_notes/1.0.2.md
  release_notes/1.0.6.md
  release_notes/2.0.2.md
  release_notes/2.1.3.md
  release_notes/2.2.1.md
  release_notes/2.2.2.md
  release_notes/release_notes.html
Labels: certified, splunk-supported

#4 Mattermost: Adding port information in the app's documentation
  readme.html
  release_notes/2.2.2.md
  release_notes/2.2.3.md
  release_notes/release_notes.html
Labels: splunk-supported
